// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_old.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hd8_kAmnjBYJ1NMgnDDjrXN1jT_y3j4',
    appId: '1:84123495621:web:9dcaa5676f8d3cb93814ac',
    messagingSenderId: '84123495621',
    projectId: 'isiproject-4a5fd',
    authDomain: 'isiproject-4a5fd.firebaseapp.com',
    storageBucket: 'isiproject-4a5fd.appspot.com',
    measurementId: 'G-M10KPSZ64G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTk4cbrYuLX6maelGr1_FVFUnE2imx_D8',
    appId: '1:84123495621:android:5e720b25e09d91513814ac',
    messagingSenderId: '84123495621',
    projectId: 'isiproject-4a5fd',
    storageBucket: 'isiproject-4a5fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TVoi-D2sW9rXsibA-_PFsnImexH5RCc',
    appId: '1:84123495621:ios:4bea4fecc23f64fa3814ac',
    messagingSenderId: '84123495621',
    projectId: 'isiproject-4a5fd',
    storageBucket: 'isiproject-4a5fd.appspot.com',
    iosBundleId: 'com.example.isiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_TVoi-D2sW9rXsibA-_PFsnImexH5RCc',
    appId: '1:84123495621:ios:4bea4fecc23f64fa3814ac',
    messagingSenderId: '84123495621',
    projectId: 'isiproject-4a5fd',
    storageBucket: 'isiproject-4a5fd.appspot.com',
    iosBundleId: 'com.example.isiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_hd8_kAmnjBYJ1NMgnDDjrXN1jT_y3j4',
    appId: '1:84123495621:web:683bdb33b23ae8c23814ac',
    messagingSenderId: '84123495621',
    projectId: 'isiproject-4a5fd',
    authDomain: 'isiproject-4a5fd.firebaseapp.com',
    storageBucket: 'isiproject-4a5fd.appspot.com',
    measurementId: 'G-Q76WV42701',
  );
}
