// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxx',
    appId: 'xxxxxx',
    messagingSenderId: 'xxxx',
    projectId: 'xxxxx',
    authDomain: 'xxxx',
    storageBucket: 'xxxx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxx',
    appId: 'xxxxx',
    messagingSenderId: 'xxxxx',
    projectId: 'xxxxx',
    storageBucket: 'xxxxx',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxx',
    appId: 'xxxxx',
    messagingSenderId: 'xxxxx',
    projectId: 'xxxxx',
    storageBucket: 'xxxxx',
    iosBundleId: 'xxxxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxx',
    appId: 'xxxxx',
    messagingSenderId: 'xxxxx',
    projectId: 'xxxxx',
    storageBucket: 'xxxxx',
    iosBundleId: 'xxxxx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'xxxxx',
    appId: 'xxxxx',
    messagingSenderId: 'xxxxx',
    projectId: 'xxxxx',
    authDomain: 'xxxxx',
    storageBucket: 'xxxxx',
  );
}
