// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRmGbyT-rHKA5hdc1AFS-pzKxfHmNs5I',
    appId: '1:808434437052:web:caa044a0a1607daf6fb9b9',
    messagingSenderId: '808434437052',
    projectId: 'isiproject-ae546',
    authDomain: 'isiproject-ae546.firebaseapp.com',
    storageBucket: 'isiproject-ae546.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMKedC3MXDnxLd0JA0Hdumq0xC3s1Hh10',
    appId: '1:808434437052:android:4ad00e64f4f084856fb9b9',
    messagingSenderId: '808434437052',
    projectId: 'isiproject-ae546',
    storageBucket: 'isiproject-ae546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jyQWzu-5CsfB20d3nNkazH_cHWCK1KU',
    appId: '1:808434437052:ios:84bb3b862bc5c8a26fb9b9',
    messagingSenderId: '808434437052',
    projectId: 'isiproject-ae546',
    storageBucket: 'isiproject-ae546.appspot.com',
    iosBundleId: 'com.example.isiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jyQWzu-5CsfB20d3nNkazH_cHWCK1KU',
    appId: '1:808434437052:ios:84bb3b862bc5c8a26fb9b9',
    messagingSenderId: '808434437052',
    projectId: 'isiproject-ae546',
    storageBucket: 'isiproject-ae546.appspot.com',
    iosBundleId: 'com.example.isiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeRmGbyT-rHKA5hdc1AFS-pzKxfHmNs5I',
    appId: '1:808434437052:web:2fb6c0dab8960e386fb9b9',
    messagingSenderId: '808434437052',
    projectId: 'isiproject-ae546',
    authDomain: 'isiproject-ae546.firebaseapp.com',
    storageBucket: 'isiproject-ae546.appspot.com',
  );
}
